name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    name: "Dependency Graph"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit
      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: 'Checkout Repository'
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Linux requirements
        run: sudo apt-get -y install texinfo
      - name: Build JNA Libraries
        run: |
          ant dist
      - name: "Submit Dependency Snapshot (JNA)"
        uses: advanced-security/maven-dependency-submission-action@5d0f9011b55d6268922128af45275986303459c3 # v4.0.3
        with:
          directory: build
          maven-args: '-f pom-jna.xml'
      - name: "Submit Dependency Snapshot (JNA JPMS)"
        uses: advanced-security/maven-dependency-submission-action@5d0f9011b55d6268922128af45275986303459c3 # v4.0.3
        with:
          directory: build
          maven-args: '-f pom-jna-jpms.xml'
      - name: "Submit Dependency Snapshot (JNA GraalVM)"
        uses: advanced-security/maven-dependency-submission-action@5d0f9011b55d6268922128af45275986303459c3 # v4.0.3
        with:
          directory: build
          maven-args: '-f pom-jna-graalvm.xml'
      - name: "Submit Dependency Snapshot (JNA Platform)"
        uses: advanced-security/maven-dependency-submission-action@5d0f9011b55d6268922128af45275986303459c3 # v4.0.3
        with:
          directory: build
          maven-args: '-f pom-jna-platform.xml'
      - name: "Submit Dependency Snapshot (JNA JPMS Platform)"
        uses: advanced-security/maven-dependency-submission-action@5d0f9011b55d6268922128af45275986303459c3 # v4.0.3
        with:
          directory: build
          maven-args: '-f pom-jna-platform-jpms.xml'

  dependency-review:
    runs-on: ubuntu-latest
    needs: [dependency-graph]
    name: "Dependency Review"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit
      - name: 'Checkout Repository'
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@0efb1d1d84fc9633afcdaad14c485cbbc90ef46c # v2.5.1
