# GraalVM build and native test.
name: GraalVM CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Native (JDK 21, ubuntu-latest)

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Linux requirements
        run: sudo apt-get -y install texinfo
      - name: macOS requirements
        if: false
        run: |
          brew update
          brew install automake --force
          brew install libtool --force
          brew install texinfo --force
      - uses: gradle/actions/setup-gradle@v3
      - name: "Build: Native Image"
        run: ant dist && ant install && ant nativeImage && ant nativeRun
