name: Maven Bundle

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build-maven-bundle:
    runs-on: ubuntu-latest
    name: Maven Bundle
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Linux requirements
        run: sudo apt-get -y install texinfo
      - name: Local Build & Deploy
        run: ant deploy-local
      - uses: actions/upload-artifact@v4
        with:
          name: jna-maven-bundle-${{ github.sha }}
          path: build/stage
          if-no-files-found: error
          retention-days: 14
          compression-level: 1
          overwrite: true
